feat: upload-landingPage
mhechavarria/playground pull request #13
Opened 2023-06-05 18:38 UTC by Fran-chess

2023-06-05 21:24 UTC, mhechavarria requested changes

2023-06-05 21:24 UTC, mhechavarria commented on Francisco/MarvelHeroes/styles.css
> +nav ul li {
Es buena práctica no dejar código comentado, si podes borralo.

2023-06-05 21:24 UTC, mhechavarria commented on Francisco/MarvelHeroes/index.html
> +      <!-- <nav>
Borrar código comentado.

2023-06-06 00:42 UTC, cerveux approved these changes
LGTM

2023-06-06 12:34 UTC, mhechavarria requested changes

2023-06-06 19:23 UTC, mhechavarria approved these changes
LGTM

2023-06-06 20:51 UTC, GYauck approved these changes
LGTM

2023-06-07 21:26 UTC, merged