feat: first assignment - marvel hero
mhechavarria/playground pull request #9
Opened 2023-06-02 19:44 UTC by marianowadi

2023-06-02 20:42 UTC, mhechavarria approved these changes
Looks mysterious and good to me

2023-06-02 20:54 UTC, JulianaCotabarren reviewed
Hola Mariano, no sé si era la intención que saltáramos con esta revisión pero hago el comentario por las dudas para no quedarme con la espina jaja. Si bien el código parece funcional no se estaría aplicando HTML semántico, ya que en lugar de utilizar las etiquetas header, main y footer se están utilizando div con roles...

2023-06-04 02:48 UTC, GYauck requested changes
Should change some tags to semantic HTML

2023-06-06 15:35 UTC, GYauck approved these changes

2023-06-07 14:55 UTC, JulianaCotabarren approved these changes
LGTM
(Se podría mejorar poniendo el nav dentro de un header)

2023-06-07 23:01 UTC, TomiOliva commented
LGTM

2023-06-08 17:22 UTC, merged